highlighter: pygments
markdown: rdiscount
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
port: 3000
safe: true
timezone: Europe/Warsaw

url: http://zippydesk.github.io/
baseurl: /ft2016/
title: "Front-Trends 2016"
name: "Front-Trends 2016"
author: Pawe≈Ç Czerski
description: "Front-Trends 2016: May 18-20, 2016 in Warsaw, Poland"
avatar: profile.png
email: contact@front-trends.com
twitter: fronttrends
google_analytics: UA-54477891-2
